'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class FirstAidJournal
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.FirstAidJournal", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log ud.
        '''</summary>
        Friend Shared ReadOnly Property AccountLogOff() As String
            Get
                Return ResourceManager.GetString("AccountLogOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log ind.
        '''</summary>
        Friend Shared ReadOnly Property AccountLogOn() As String
            Get
                Return ResourceManager.GetString("AccountLogOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alder.
        '''</summary>
        Friend Shared ReadOnly Property Age() As String
            Get
                Return ResourceManager.GetString("Age", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alle hold.
        '''</summary>
        Friend Shared ReadOnly Property AllTeams() As String
            Get
                Return ResourceManager.GetString("AllTeams", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Førstehjælpslog.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationTitle() As String
            Get
                Return ResourceManager.GetString("ApplicationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Område.
        '''</summary>
        Friend Shared ReadOnly Property Area() As String
            Get
                Return ResourceManager.GetString("Area", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afbryd.
        '''</summary>
        Friend Shared ReadOnly Property BackToList() As String
            Get
                Return ResourceManager.GetString("BackToList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opret.
        '''</summary>
        Friend Shared ReadOnly Property CommandCreate() As String
            Get
                Return ResourceManager.GetString("CommandCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slet.
        '''</summary>
        Friend Shared ReadOnly Property CommandDelete() As String
            Get
                Return ResourceManager.GetString("CommandDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gem.
        '''</summary>
        Friend Shared ReadOnly Property CommandSave() As String
            Get
                Return ResourceManager.GetString("CommandSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redigér skade.
        '''</summary>
        Friend Shared ReadOnly Property EditEvent() As String
            Get
                Return ResourceManager.GetString("EditEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the form below to create a new account..
        '''</summary>
        Friend Shared ReadOnly Property EnterAccountInformation() As String
            Get
                Return ResourceManager.GetString("EnterAccountInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ny skade.
        '''</summary>
        Friend Shared ReadOnly Property EventCreate() As String
            Get
                Return ResourceManager.GetString("EventCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skade.
        '''</summary>
        Friend Shared ReadOnly Property EventDetails() As String
            Get
                Return ResourceManager.GetString("EventDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Færdig.
        '''</summary>
        Friend Shared ReadOnly Property EventFinished() As String
            Get
                Return ResourceManager.GetString("EventFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to skader.
        '''</summary>
        Friend Shared ReadOnly Property EventPlural() As String
            Get
                Return ResourceManager.GetString("EventPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to skade.
        '''</summary>
        Friend Shared ReadOnly Property EventSingular() As String
            Get
                Return ResourceManager.GetString("EventSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skader.
        '''</summary>
        Friend Shared ReadOnly Property EventsListTitle() As String
            Get
                Return ResourceManager.GetString("EventsListTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kvinde.
        '''</summary>
        Friend Shared ReadOnly Property Female() As String
            Get
                Return ResourceManager.GetString("Female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Køn.
        '''</summary>
        Friend Shared ReadOnly Property Gender() As String
            Get
                Return ResourceManager.GetString("Gender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tilføj.
        '''</summary>
        Friend Shared ReadOnly Property GeneralAdd() As String
            Get
                Return ResourceManager.GetString("GeneralAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opret ny.
        '''</summary>
        Friend Shared ReadOnly Property GeneralCreate() As String
            Get
                Return ResourceManager.GetString("GeneralCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slet.
        '''</summary>
        Friend Shared ReadOnly Property GeneralDelete() As String
            Get
                Return ResourceManager.GetString("GeneralDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detaljer.
        '''</summary>
        Friend Shared ReadOnly Property GeneralDetails() As String
            Get
                Return ResourceManager.GetString("GeneralDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redigér.
        '''</summary>
        Friend Shared ReadOnly Property GeneralEdit() As String
            Get
                Return ResourceManager.GetString("GeneralEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Behandler.
        '''</summary>
        Friend Shared ReadOnly Property Helper() As String
            Get
                Return ResourceManager.GetString("Helper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} if you don&apos;t have an account..
        '''</summary>
        Friend Shared ReadOnly Property IfYouDontHaveLogin() As String
            Get
                Return ResourceManager.GetString("IfYouDontHaveLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skadetype.
        '''</summary>
        Friend Shared ReadOnly Property Injury() As String
            Get
                Return ResourceManager.GetString("Injury", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        '''</summary>
        Friend Shared ReadOnly Property LoginUnsuccessful() As String
            Get
                Return ResourceManager.GetString("LoginUnsuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mand.
        '''</summary>
        Friend Shared ReadOnly Property Male() As String
            Get
                Return ResourceManager.GetString("Male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktiviteter.
        '''</summary>
        Friend Shared ReadOnly Property MenuActivity() As String
            Get
                Return ResourceManager.GetString("MenuActivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Områder.
        '''</summary>
        Friend Shared ReadOnly Property MenuArea() As String
            Get
                Return ResourceManager.GetString("MenuArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skader.
        '''</summary>
        Friend Shared ReadOnly Property MenuEvent() As String
            Get
                Return ResourceManager.GetString("MenuEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend Shared ReadOnly Property MenuHome() As String
            Get
                Return ResourceManager.GetString("MenuHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skadetyper.
        '''</summary>
        Friend Shared ReadOnly Property MenuInjury() As String
            Get
                Return ResourceManager.GetString("MenuInjury", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personer.
        '''</summary>
        Friend Shared ReadOnly Property MenuPerson() As String
            Get
                Return ResourceManager.GetString("MenuPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hold.
        '''</summary>
        Friend Shared ReadOnly Property MenuTeam() As String
            Get
                Return ResourceManager.GetString("MenuTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Behandlinger.
        '''</summary>
        Friend Shared ReadOnly Property MenuTreatment() As String
            Get
                Return ResourceManager.GetString("MenuTreatment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kategorier.
        '''</summary>
        Friend Shared ReadOnly Property MenuTreatmentCategory() As String
            Get
                Return ResourceManager.GetString("MenuTreatmentCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navn.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Noter.
        '''</summary>
        Friend Shared ReadOnly Property Notes() As String
            Get
                Return ResourceManager.GetString("Notes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adgangskoden skal mindst være {0} tegn lang..
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequirements() As String
            Get
                Return ResourceManager.GetString("PasswordRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Udført.
        '''</summary>
        Friend Shared ReadOnly Property Performed() As String
            Get
                Return ResourceManager.GetString("Performed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person.
        '''</summary>
        Friend Shared ReadOnly Property Person() As String
            Get
                Return ResourceManager.GetString("Person", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Er du sikker på at du vil slette denne person og alle registrerede skader?.
        '''</summary>
        Friend Shared ReadOnly Property PersonAreYouSure() As String
            Get
                Return ResourceManager.GetString("PersonAreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opret ny person.
        '''</summary>
        Friend Shared ReadOnly Property PersonCreate() As String
            Get
                Return ResourceManager.GetString("PersonCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slet person.
        '''</summary>
        Friend Shared ReadOnly Property PersonDelete() As String
            Get
                Return ResourceManager.GetString("PersonDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redigér person.
        '''</summary>
        Friend Shared ReadOnly Property PersonEdit() As String
            Get
                Return ResourceManager.GetString("PersonEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personer.
        '''</summary>
        Friend Shared ReadOnly Property PersonListTitle() As String
            Get
                Return ResourceManager.GetString("PersonListTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter user name and password..
        '''</summary>
        Friend Shared ReadOnly Property PleaseEnterUsernameAndPassword() As String
            Get
                Return ResourceManager.GetString("PleaseEnterUsernameAndPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register.
        '''</summary>
        Friend Shared ReadOnly Property Register() As String
            Get
                Return ResourceManager.GetString("Register", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skift.
        '''</summary>
        Friend Shared ReadOnly Property SwitchTeam() As String
            Get
                Return ResourceManager.GetString("SwitchTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hold.
        '''</summary>
        Friend Shared ReadOnly Property Team() As String
            Get
                Return ResourceManager.GetString("Team", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktivér.
        '''</summary>
        Friend Shared ReadOnly Property TeamActivate() As String
            Get
                Return ResourceManager.GetString("TeamActivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktivt.
        '''</summary>
        Friend Shared ReadOnly Property TeamActive() As String
            Get
                Return ResourceManager.GetString("TeamActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Er du sikker på, du vil slette dette hold?.
        '''</summary>
        Friend Shared ReadOnly Property TeamAreYouSure() As String
            Get
                Return ResourceManager.GetString("TeamAreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opret nyt hold.
        '''</summary>
        Friend Shared ReadOnly Property TeamCreate() As String
            Get
                Return ResourceManager.GetString("TeamCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slet hold.
        '''</summary>
        Friend Shared ReadOnly Property TeamDelete() As String
            Get
                Return ResourceManager.GetString("TeamDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Holddata.
        '''</summary>
        Friend Shared ReadOnly Property TeamDetails() As String
            Get
                Return ResourceManager.GetString("TeamDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redigér hold.
        '''</summary>
        Friend Shared ReadOnly Property TeamEdit() As String
            Get
                Return ResourceManager.GetString("TeamEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dette er dit aktive hold.
        '''</summary>
        Friend Shared ReadOnly Property TeamIsActive() As String
            Get
                Return ResourceManager.GetString("TeamIsActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Din ansøgning om medlemsskab afventer bekræftelse.
        '''</summary>
        Friend Shared ReadOnly Property TeamIsPending() As String
            Get
                Return ResourceManager.GetString("TeamIsPending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ansøg om medlemsskab.
        '''</summary>
        Friend Shared ReadOnly Property TeamJoin() As String
            Get
                Return ResourceManager.GetString("TeamJoin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bekræft.
        '''</summary>
        Friend Shared ReadOnly Property TeamMemberConfirm() As String
            Get
                Return ResourceManager.GetString("TeamMemberConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Degradér.
        '''</summary>
        Friend Shared ReadOnly Property TeamMemberDemote() As String
            Get
                Return ResourceManager.GetString("TeamMemberDemote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Udeluk.
        '''</summary>
        Friend Shared ReadOnly Property TeamMemberKick() As String
            Get
                Return ResourceManager.GetString("TeamMemberKick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forfrem til holdleder.
        '''</summary>
        Friend Shared ReadOnly Property TeamMemberPromote() As String
            Get
                Return ResourceManager.GetString("TeamMemberPromote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medlemmer.
        '''</summary>
        Friend Shared ReadOnly Property TeamMembers() As String
            Get
                Return ResourceManager.GetString("TeamMembers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Holdnavn.
        '''</summary>
        Friend Shared ReadOnly Property TeamName() As String
            Get
                Return ResourceManager.GetString("TeamName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidspunkt.
        '''</summary>
        Friend Shared ReadOnly Property Timestamp() As String
            Get
                Return ResourceManager.GetString("Timestamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Behandling.
        '''</summary>
        Friend Shared ReadOnly Property Treatments() As String
            Get
                Return ResourceManager.GetString("Treatments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User name.
        '''</summary>
        Friend Shared ReadOnly Property UserName() As String
            Get
                Return ResourceManager.GetString("UserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velkommen.
        '''</summary>
        Friend Shared ReadOnly Property Welcome() As String
            Get
                Return ResourceManager.GetString("Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dine hold.
        '''</summary>
        Friend Shared ReadOnly Property YourTeams() As String
            Get
                Return ResourceManager.GetString("YourTeams", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
